version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:                               
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t pensioner-detail-service .
      - docker tag pensioner-detail-service 860061945305.dkr.ecr.ap-south-1.amazonaws.com/2040566-pms-pensioner-detail-service-ecr:detail
  post_build:
    commands:
      - echo Build completed on `date`   
      - docker push 860061945305.dkr.ecr.ap-south-1.amazonaws.com/2040566-pms-pensioner-detail-service-ecr:detail
      - echo Writing definition files
      - printf '[{"name":"pms-pensioner-detail-service-container-2040566","imageUri":"%s"}]' 860061945305.dkr.ecr.ap-south-1.amazonaws.com/2040566-pms-pensioner-detail-service-ecr:detail > taskdefinition.json

artifacts:
  files: taskdefinition.json
