version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd pensioner-detail-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t pensioner-detail-service .
      - docker tag pensioner-detail-service 421308774925.dkr.ecr.us-east-1.amazonaws.com/pod4-service-registry:pensioner-detail-service
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 421308774925.dkr.ecr.us-east-1.amazonaws.com/pod4-service-registry:pensioner-detail-service
      - echo Writing definition files
      - printf '[{"name":"ij026-pod4-pensioner-detail-service-container","imageUri":"%s"}]' 421308774925.dkr.ecr.us-east-1.amazonaws.com/pod4-service-registry:pensioner-detail-service > taskdefinition.json

artifacts:
  files: pensioner-detail-service/taskdefinition.json